name: pomodoro_prodigy
description: Aplicação de gestão de tempo utilizando a técnica pomodoro
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.2
  provider: ^6.0.5
  google_fonts: ^5.1.0

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pomodoro
      fonts:
        - asset: assets/fonts/Pomodoro.ttf